# Generated by Django 2.1.3 on 2019-01-31 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('A', 'Conferencia'), ('B', 'Seminario'), ('C', 'Congreso'), ('D', 'Curso')], max_length=1)),
                ('lugar', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('A', 'Presencial'), ('B', 'Virtual')], max_length=1)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
